spring:
  application:
    name: UJSU
  datasource:
      generate-unique-name: false
      name: UJSU
      url: ${UJSU_MYSQL_URL:jdbc:mysql://localhost:3306/UJSU}
      username: ${UJSU_MYSQL_USERNAME:ujsu}
      password: ${UJSU_MYSQL_PASSWORD:ujsupass}
      driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    baseline-version: 10
    user: ${UJSU_MYSQL_USERNAME:ujsu}
    password: ${UJSU_MYSQL_PASSWORD:ujsupass}
  cache:
    type: simple

server:
   port: 8080