spring:
  application:
      name: UJSU
  datasource:
      generate-unique-name: false
      name: ujsu
      url: ${UJSU_MYSQL_URL:jdbc:mysql://localhost:3306/ujsu}
      username: ${UJSU_MYSQL_USERNAME:ujsu}
      password: ${UJSU_MYSQL_PASSWORD:ujsupass}
      driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
server:
  port: 8080
logging:
  level:
    org:
      springframework:
        data:
          jdbc: DEBUG
        jdbc:
          core: DEBUG
        security: DEBUG