spring:
  application:
      name: UJSU
  datasource:
      generate-unique-name: false
      name: ujsu
      url: ${UJSU_MYSQL_URL:jdbc:mysql://localhost:3306/ujsu}
      username: ${UJSU_MYSQL_USERNAME:ujsu}
      password: ${UJSU_MYSQL_PASSWORD:ujsupass}
      driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    baseline-on-migrate: true
    baseline-version: 2
server:
   port: 8080
logging:
  level:
     org:
       springframework:
         data:
           convert: DEBUG
           jdbc:
             core:
               convert:
                 JdbcConverter: DEBUG
         jdbc:
           core: DEBUG
         security: DEBUG
#spring:
#  application:
#    name: UJSU
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password: 
#    driver-class-name: org.h2.Driver
#  h2:
#    console:
#      enabled: true
#  sql:
#    init:
#      schema-locations: classpath:schema.sql
#      data-locations: classpath:university.sql
#      mode: never
#      
#  thymeleaf:
#    cache: false
#
#server:
#  port: 8080
#
#logging:
#  level:
#    org:
#      springframework:
#        data:
#          jdbc: DEBUG
#        jdbc:
#          core: DEBUG
#        security: DEBUG
